import type { Metadata } from "next";
import Link from "next/link";
import { AssetGallery } from "@/components/asset-gallery";
import { processSteps, services } from "@/lib/content";
export const metadata:Metadata={alternates:{canonical:"/"}};
export default function Home(){return <main id="main">
  <section className="technical-grid overflow-hidden bg-[var(--ink)] py-14 text-white sm:py-24"><div className="wrap"><p className="eyebrow text-[var(--brand)]">Sydney · Powder coating of metal parts</p><div className="mt-7 grid items-end gap-12 lg:grid-cols-[1.35fr_.65fr]"><h1 className="display">Industrial<br/><span className="text-[var(--brand)]">Finishes.</span></h1><div className="border-l-4 border-[var(--brand)] pl-6"><p className="text-xl leading-relaxed text-white/80">Professional powder coating for custom fabrications, architectural metalwork and production batches across Sydney.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/quote" className="button button-brand">Request a Quote <span aria-hidden>→</span></Link><Link href="/projects" className="button button-outline">View Our Work</Link></div></div></div></div></section>
  <section className="py-16 sm:py-20"><div className="wrap"><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-[var(--brand-dark)]">What we coat</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Built for varied metalwork.</h2></div><Link href="/services" className="font-bold underline decoration-[var(--brand)] decoration-2 underline-offset-4">View services →</Link></div><div className="grid border-y border-[var(--line)] sm:grid-cols-2 lg:grid-cols-3">{services.slice(0,3).map((s,i)=><article key={s.title} className="p-6 lg:border-r lg:last:border-r-0"><span className="eyebrow text-[var(--brand-dark)]">0{i+1}</span><h3 className="mt-8 text-2xl font-bold">{s.title}</h3><p className="mt-3 leading-relaxed text-[var(--muted)]">{s.copy}</p></article>)}</div></div></section>
  <section className="bg-white py-16 sm:py-24"><div className="wrap grid gap-12 lg:grid-cols-2"><div><p className="eyebrow text-[var(--brand-dark)]">Process before promises</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-6xl">A good finish starts before the powder.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-[var(--muted)]">Preparation, contamination control, hanging, application, curing, cooling and handling all affect the final result. Each job is assessed around the actual part—not a blanket promise.</p><Link href="/process" className="button mt-8">Explore our process →</Link></div><div>{processSteps.slice(0,4).map(([n,t,c])=><div key={n} className="grid grid-cols-[3rem_1fr] gap-4 border-t border-[var(--line)] py-5"><span className="eyebrow text-[var(--brand-dark)]">{n}</span><div><h3 className="text-xl font-bold">{t}</h3><p className="mt-2 text-[var(--muted)]">{c}</p></div></div>)}</div></div></section>
  <section className="py-16 sm:py-24"><div className="wrap"><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-[var(--brand-dark)]">Selected work</p><h2 className="mt-4 text-4xl font-black tracking-tight">Finished with purpose.</h2></div><Link href="/projects" className="font-bold underline decoration-[var(--brand)] decoration-2 underline-offset-4">View all projects →</Link></div><AssetGallery folder="projects" limit={6}/></div></section>
  <section className="border-y border-[var(--line)] bg-white py-14"><div className="wrap"><p className="eyebrow mb-8 text-center text-[var(--muted)]">Companies we have worked with · logos shown only with approval</p><AssetGallery folder="client-logos"/></div></section>
  <section className="bg-[var(--brand)] py-16"><div className="wrap grid gap-8 lg:grid-cols-[1fr_.65fr]"><div><p className="eyebrow">Ready for review?</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-6xl">Send us the job details.</h2></div><div><p className="text-lg font-medium">Photos, drawings, dimensions, material, quantity, colour and timing help us understand the work and quote it properly.</p><Link href="/quote" className="button mt-7">Request a Quote →</Link></div></div></section>
  </main>}
