import type { Metadata } from "next";
import { PageHero } from "@/components/page-hero";
import { business } from "@/lib/business";

export const metadata: Metadata = { title: "Website Terms", alternates: { canonical: "/terms" } };

export default function Terms() {
  return <main id="main">
    <PageHero label="Website terms" title="Website Terms of Use" intro="These terms apply when you use the FLOWCOAT website or send us an online enquiry or quote request." />
    <article className="wrap max-w-4xl space-y-10 py-14 text-[var(--muted)]">
      <p className="text-sm">Last updated: 14 September 2026</p>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">1. About these terms</h2><p>This website is operated under the FLOWCOAT business name. By using it, you agree to these Website Terms of Use. Separate quotation, order, payment, warranty or trading terms may apply if you later engage FLOWCOAT to supply services.</p><p>If these terms conflict with a mandatory right that cannot lawfully be excluded, that mandatory right prevails.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">2. Website information</h2><p>The website provides general information about FLOWCOAT, powder coating and the kinds of work we may consider. Suitability, preparation, coating system, colour availability, finish, timing, dimensions, pricing and other job details depend on the actual parts and must be confirmed for each job.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">3. Quote requests are not accepted orders</h2><p>Submitting a quote request, email, message, photograph, drawing or other enquiry does not create an accepted order, guarantee availability, reserve production time or bind FLOWCOAT to a price or completion date.</p><p>A job becomes binding only when the scope and commercial terms are agreed through the applicable quotation, order confirmation or other written agreement.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">4. Information you provide</h2><p>You are responsible for providing information that is accurate and reasonably complete, including relevant dimensions, material, quantity, condition, coating requirements, critical surfaces, timing and any known special handling requirements.</p><p>If you provide photographs, drawings, logos or other material, you confirm that you are entitled to provide it for the requested purpose. Do not submit highly sensitive or confidential material through a website feature unless that feature is specifically identified as suitable for secure submission.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">5. Intellectual property</h2><p>Unless otherwise stated, the website design, written content and FLOWCOAT branding are owned by or licensed to FLOWCOAT. Third-party names, trade marks and logos remain the property of their respective owners.</p><p>You may use the website for ordinary personal or business enquiry purposes. You must not reproduce, republish, sell, modify or commercially exploit substantial website content without permission, except where the law allows it.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">6. Acceptable use</h2><p>You must not interfere with website security or availability, attempt unauthorised access, submit unlawful content, impersonate another person or use automated systems in a way that places an unreasonable load on the website.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">7. Third-party services</h2><p>The website may link to services such as Instagram or other external websites. Those services are controlled by their operators and have their own terms and privacy practices.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">8. Availability</h2><p>We may change, suspend or withdraw website features at any time. We do not promise that the website will always be uninterrupted or error-free, although we take reasonable steps to operate and protect it.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">9. Consumer rights and liability</h2><p>Nothing in these terms excludes, restricts or modifies any guarantee, right or remedy that cannot lawfully be excluded, including rights that may apply under the Australian Consumer Law.</p><p>To the maximum extent permitted by law, FLOWCOAT is not responsible for indirect loss arising solely from reliance on general information on this website. This does not limit liability that cannot legally be limited or excluded.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">10. Privacy</h2><p>Personal information handled through the website is dealt with in accordance with our <a className="font-bold text-[var(--ink)] underline" href="/privacy">Privacy Policy</a>.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">11. Changes</h2><p>We may update these terms from time to time. The version published on this page applies from its stated update date. Changes do not retrospectively alter an already agreed customer contract unless the parties agree or the law provides otherwise.</p></section>
      <section className="space-y-3"><h2 className="text-2xl font-black text-[var(--ink)]">12. Governing law and contact</h2><p>These website terms are governed by the laws applicable in New South Wales, Australia, subject to any mandatory law that applies otherwise.</p><p>Questions can be sent to <a className="font-bold text-[var(--ink)] underline" href={`mailto:${business.email}`}>{business.email}</a>, by phone on <a className="font-bold text-[var(--ink)] underline" href={`tel:${business.phoneHref}`}>{business.phoneDisplay}</a>, or to {business.addressDisplay}.</p></section>
    </article>
  </main>;
}
